### ISSUE TITLE
Backticks passed to HTML Webpack Plugin causing errors

### ISSUE THREAD

**Issue by kuanb** [interra/catalog-generate#22]
# Interra Catalog Generate 

## Issue Type
Bug

## Description

The following error is thrown when running `node cli.js build-site site` where `site` is the example test site from `internal/`, copied into sites:
```
ERROR in 1.3784428a53aabf77856b.chunk.js from UglifyJs
Unexpected character '`' [1.3784428a53aabf77856b.chunk.js:9791,18]
```

The error appears because of this line in one of the chunked additional `.js` blobs:
```
    if (typeof callback !== 'function') {
      throw Error(`Invalid callback argument: ${JSON.stringify(callback)}`);
    }
    if (!(typeof data === 'string' || Buffer.isBuffer(arguments[0]))) {
      return callback(Error(`Invalid data argument: ${JSON.stringify(data)}`));
    }
```

It appears there is no step to deal with converting template literals. I thought I could adding `transform-es2015-template-literals` to the babel key in the `package.json`. Unfortunately, the operation did not appear to run. I suspected this might be because it is not being passed to `webpack.base.babel` as an option in `webpack.prod.babel`. 

I notice that in the script of `base`, it calls `babel-loader` with options from `options.babelQuery`, which is not defined. I wondered if passing in the `production` variables from the `babel` key in `pacakge.json` would help here, but no luck either.

## Steps to reproduce

Run `node cli.js build-site test-site`, where `test-site` is just the one from `test/` copy and pasted over to the `site/` directory.

# Versions

- Node/NPM: Node 8.9.4, npm 5.6.0
- Browser: No browser

**Comment by kuanb** [comment]
Just an update, I can recreate this by running `node cli.js build-site` on either of the sites in the `sites/` dir already in the repo, as well, which makes me think it is related to the webpack/babel configuration. But, it looks like this pretty much follows what `react-boilerplate` has, so if that were the case I would also expect the issue to be easily searched/google-able, yet it isn't. 🤔

**Comment by acouch** [comment]
Yes I think this is a webpack issue maybe with uglify or babel version? I built from master a  week or so ago for a demo but didn't have that problem. I noticed that even though it threw the error the build still worked.

I will try and dig more into this on Sunday.

**Comment by AlexanderTserkovniy** [comment]
Same issue here, please advise.

**Comment by acouch** [comment]
This was due to [node-csv-parser including template literals](https://github.com/adaltas/node-csv-parse/issues/165) in their 2.x release. Not sure why this didn't appear when I introduced the csv parser but #24 cleans that up.
